#@TYPE: Machine
#@NAME: Beaglebone 
#@DESCRIPTION: Machine configuration for the Beaglebone specifically for rootbot project

SOC_FAMILY = "ti335x"
TARGET_ARCH = "arm"

DEFAULTTUNE ?= "cortexa8hf-neon"

require conf/machine/include/ti33x.inc

MACHINE_EXTRA_RRECOMMENDS = " kernel-modules kernel-devicetree"

# not yet working, to be fixed!
KERNEL_MODULE_AUTOLOAD += " \
	hcsr04 \
	stepperL \
	stepperR \
	st7565 \
"

PREFERRED_PROVIDER_virtual/kernel = "linux-ti-staging"
# not yet tested
#PREFERRED_PROVIDER_virtual/kernel = "linux-ti-staging-rt"

PREFERRED_PROVIDER_virtual/bootloader = "u-boot-ti-staging"
PREFERRED_PROVIDER_u-boot = "u-boot-ti-staging"

# not sure why this does not work in kernel recipe
#KERNEL_DEVICETREE = " \
#   am335x-boneblack-rootbot.dtb \
#   rootbot-beagleboneblack.dtb \
#   am335x-boneblack.dtb \
#"

UBOOT_ENTRYPOINT = "0x80008000"
UBOOT_LOADADDRESS = "0x80008000"
#UBOOT_MACHINE = "am335x_evm_defconfig"
BOOTENV_SIZE = "0x20000"

SERIAL_CONSOLES ?= "115200;ttyS0 115200;ttyO0"
SERIAL_CONSOLES_CHECK = "${SERIAL_CONSOLES}"

IMAGE_BOOT_FILES:append = "zImage MLO extlinux.conf"
#EXTRA_IMAGEDEPENDS += "u-boot"
#EXTRA_IMAGEDEPENDS:append = "u-boot-ti-staging"

MACHINE_FEATURES = "serial usbhost vfat"

MACHINE_FEATURES:remove = "alsa"
MACHINE_FEATURES:remove = "alsa-lib"
MACHINE_FEATURES:remove = "alsa-state"
MACHINE_FEATURES:remove = "alsa-utils"
MACHINE_FEATURES:remove = "apm"
MACHINE_FEATURES:remove = "gpu"
MACHINE_FEATURES:remove = "qemu-user-mode"
