driftfile /var/lib/ntp/drift

server 127.127.1.0
fudge 127.127.1.0 stratum 14

restrict -4 default notrap nomodify nopeer noquery
restrict -6 default notrap nomodify nopeer noquery

server 0.pool.ntp.org iburst
server 1.pool.ntp.org iburst
server 2.pool.ntp.org iburst
server 3.pool.ntp.org iburst

restrict 127.0.0.1    # allow local host
restrict ::1          # allow local host
